"""Facial Visagism Analysis System.

A computer vision application that processes frontal face photographs
to identify facial landmarks, calculate proportions, classify face shape,
and compare measurements against the golden ratio.
"""

from __future__ import annotations

from visagism.constants import (
    BBOX_EXPANSION_FACTOR,
    DEVIATION_THRESHOLD,
    ENV_DLIB_MODEL_PATH,
    GOLDEN_RATIO,
    HAAR_MIN_FACE_SIZE,
    HAAR_MIN_NEIGHBORS,
    HAAR_SCALE_FACTOR,
    HAIRLINE_CANNY_HIGH,
    HAIRLINE_CANNY_LOW,
    HAIRLINE_CLAHE_CLIP,
    HAIRLINE_CLAHE_GRID,
    HAIRLINE_MIN_GRADIENT_RATIO,
    HAIRLINE_ROI_UPWARD_EXPANSION,
    HAIRLINE_ROI_WIDTH_RATIO,
    LANDMARK_LINE_THICKNESS,
    LANDMARK_POINT_RADIUS,
    LEGEND_ALPHA,
    LEGEND_BG_COLOR,
    LEGEND_FONT_SCALE,
    LEGEND_FONT_THICKNESS,
    LEGEND_LINE_HEIGHT,
    LEGEND_MARGIN,
    MIN_RESOLUTION,
    OUTPUT_DIR,
    REGION_COLORS,
    REGION_CONNECTIONS,
    REGION_INDICES,
    REGION_LABELS,
    SMALL_FACE_AREA_THRESHOLD,
    SUPPORTED_FORMATS,
)
from visagism.errors import (
    AnalysisError,
    CorruptedImageError,
    DetectionError,
    ImageError,
    InvalidLandmarksError,
    ModelError,
    ModelNotFoundError,
    NoFaceDetectedError,
    UnsupportedFormatError,
    VisagismError,
)
from visagism.hairline_detector import HairlineDetector
from visagism.types import (
    FaceRect,
    FacialLandmarks,
    ImageArray,
    LandmarkRegions,
    LandmarksList,
    Point,
)

__all__ = [
    # Constants
    "BBOX_EXPANSION_FACTOR",
    "DEVIATION_THRESHOLD",
    "ENV_DLIB_MODEL_PATH",
    "GOLDEN_RATIO",
    "HAAR_MIN_FACE_SIZE",
    "HAAR_MIN_NEIGHBORS",
    "HAAR_SCALE_FACTOR",
    "HAIRLINE_CANNY_HIGH",
    "HAIRLINE_CANNY_LOW",
    "HAIRLINE_CLAHE_CLIP",
    "HAIRLINE_CLAHE_GRID",
    "HAIRLINE_MIN_GRADIENT_RATIO",
    "HAIRLINE_ROI_UPWARD_EXPANSION",
    "HAIRLINE_ROI_WIDTH_RATIO",
    "LANDMARK_LINE_THICKNESS",
    "LANDMARK_POINT_RADIUS",
    "LEGEND_ALPHA",
    "LEGEND_BG_COLOR",
    "LEGEND_FONT_SCALE",
    "LEGEND_FONT_THICKNESS",
    "LEGEND_LINE_HEIGHT",
    "LEGEND_MARGIN",
    "MIN_RESOLUTION",
    "OUTPUT_DIR",
    "REGION_COLORS",
    "REGION_CONNECTIONS",
    "REGION_INDICES",
    "REGION_LABELS",
    "SMALL_FACE_AREA_THRESHOLD",
    "SUPPORTED_FORMATS",
    # Errors
    "AnalysisError",
    "CorruptedImageError",
    "DetectionError",
    "ImageError",
    "InvalidLandmarksError",
    "ModelError",
    "ModelNotFoundError",
    "NoFaceDetectedError",
    "UnsupportedFormatError",
    "VisagismError",
    # Modules
    "HairlineDetector",
    # Types
    "FaceRect",
    "FacialLandmarks",
    "ImageArray",
    "LandmarkRegions",
    "LandmarksList",
    "Point",
]
